comment_width = 120
edition = "2021"
group_imports = "StdExternalCrate"
imports_granularity = "Item"
match_block_trailing_comma = true
max_width = 120
merge_derives = false
newline_style = "Unix"
normalize_doc_attributes = true
overflow_delimited_expr = true
tab_spaces = 4
use_small_heuristics = "Max"
use_try_shorthand = true
wrap_comments = true
